# Generated by Django 5.2.5 on 2025-08-22 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0004_alter_order_user_alter_ticket_order'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='ticket',
            constraint=models.UniqueConstraint(fields=('row', 'seat'), name='unique_row_seat'),
        ),
    ]
